### PR TITLE
Add placeholder for MoJ code style guidance discussion

### PR DESCRIPTION
**Pull request by willmcb**
PR to start a discussion of which code styles we should at the MoJ. Please see `guides/code-styles.md` for more information.

Please read the document, and comment any suggestions below.

### CODE REVIEW

**Comment by digitalronin** [comment]
I was at a ruby conference recently, and one of the presenters mentioned this gem:
https://github.com/testdouble/standard

His argument for it was that:

* creating a house style can lead to endless bike-shedding
* once created, you have to maintain it (e.g. when the language gets new syntax)
* having *a chosen style* > having the perfect style
* letting someone else choose and maintain it is a win

If there are similar tools in other languages (e.g. StandardJS), shall we just officially adopt them and call this one done?

**Comment by willmcb** [comment]
@digitalronin I had never heard the term bike-shedding before, leads to an interesting [Wikipedia article](https://en.wikipedia.org/wiki/Law_of_triviality). 

I tend to agree, it is better to have a chosen style than the perfect one (if there can even be such a thing).

I also think that using others' work makes sense. Perhaps adopting such tools is an answer.

**Comment by MatMoore** [comment]
## My take on the questions

> should we adopt other organization's style guides? gds / google etc.

This is my preference - that way we can pick something non-controversial as the default and there's less surprises when coming to a new project. Plus everything @digitalronin said.

> what tools should we use to assess style compliance (e.g. rubocop)?

I have no strong opinions here. I think we should just recommend some default tooling and teams should be free to choose something else. I think the important thing is just that teams have some kind of standard, and use tooling to enforce it.

The general approach could vary by language. For example in ruby I would recommend running a linter as part of CI so the reviewer of a PR doesn't waste time nitpicking style issues. But in Java I would expect the IDE to handle the same kind of thing.  

> should guides be advisory or mandatory?

I vote for advisory. Teams may have good reasons to diverge. Some tools/formatters make it easy for teams to customise the styles they enforce and I think that's fine. 

> should we work to apply styles retrospectively (i.e. for legacy code)?

I think we should recommend doing this but ultimately it's up to the team.

> there are various ancillary technologies that we use (YAML / HAML / ERB) should these be linted as well?

Yes, but I'd recommend picking the ones we care about the most and starting with those.

Also, since YAML has a range of applications I think it would make more sense to use style guides/linters for specific things, like terraform, rather than YAML itself.

> how should we publicise adopted styles?

As a living document that anyone can feel comfortable proposing changes to.

I think we should have language specific pages in the technical guidance that give a general steer on how we do things here, and link out to external standards/style guides/tooling we recommend. The shorter and simpler the better.

[This is another example from GDS](https://gds-way.cloudapps.digital/manuals/programming-languages/java.html) - I don't think this is perfect, but something like this is helpful when you're new to the organisation or moving between technologies and you just want to know how things are done here.

## Suggestion
Since we're talking about a few different languages here with their own communities, what if we run a small workshop for each one, and whoever turns up can have a first stab at a style guide for their language?

**Comment by sldblog** [comment]
_puts on process hat_

> We have been having discussions in the LAA Developer team about which code style guides we should use.

I think this statement implies there is a need for consistent style across repositories. Is describing the process of enforcement/recommendation part of this discussion?

**Comment by rowlando** [comment]
Thanks for kicking this discussion of @willmcb. Lots of things to think about.

I suggest we use separate GitHub issues to discuss the various topics that have arisen here. The result maybe single or multiple PRs to implement technical guidance based on the discussions.

How does that sound?

**Comment by davidread** [comment]
I'm really just echoing what @MatMoore says.

I'm all for mandating a linter for new projects. e.g. rubocop, flake8, etc, run during CI. It's simple. It embodies lots of good practices. They spot useful errors. If it's run in CI you eliminate those arguments during PR-review about arbitrary things like whitespace.

It's become so common it's one of those baseline dev practises, so arguably not impinging on the rights of teams to be in charge of their destiny.

You're right that legacy projects may well have their reasons not to follow it though - it's probably not that high on the list to fix. The biggest net benefit is with new projects - puts them on track from the start with minimal fuss.

And we probably want to give projects the flexibility to exclude rules - some *really* wind people up, like PEP8's 79 char limit. But they still benefit from the rules/linter gradually evolving and improving.

But is anyone here thinking about a 'style guide' more complicated than a linter? e.g. The [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html) is pages of wisdom, but not being automatable may just cause unnecessary tension to enforce it on a PR by PR basis, so is maybe just something to learn from.

**Comment by rowlando** [comment]
Perhaps we should lean upon this:

https://gds-way.cloudapps.digital/manuals/programming-languages.html

**Comment by jabley** [comment]
@willmcb why was this closed?

**Comment by MatMoore** [comment]
@willmcb a few us are working on creating some more guidance for Java, so I'm going to put some suggestions about code style based on this discussion.  Let me know if you want to get involved!

**Pull request closed without merging**
