### PR TITLE
Update guide to reflect preferred use of LICENCE

### PR DESCRIPTION
**Pull request by AntonyBishop**

### CODE REVIEW

**Review by NickWalt01 — APPROVED** [review]

**Comment by SteveMarshall** [comment]
@AntonyBishop Why are we changing the spelling of licence that we use from the British English version to the American English version (license)? Both are valid in GitHub, but we should probably prefer British English, I think?

**Comment by NickWalt01** [comment]
Hi @SteveMarshall it is linked to this conversation:  https://mojdt.slack.com/archives/CPVD6398C/p1651073997210949

**Comment by AntonyBishop** [comment]
I am inclined to agree @SteveMarshall. However, all the template repos use `LICENSE` which doesn't align to the current guidance. Not to mention the LICENSE on this repo was already changed to `LICENSE`. Is it worth the effort to enforce the guidance that doesn't appear to be being followed and have to ask all code owners to rename their files when the templates have been using `LICENSE` all along?

**Comment by SteveMarshall** [comment]
@AntonyBishop As I mentioned on Slack, I reckon we should:

1. Say here that we _prefer_ the British spelling, but also say that we accept the US spelling.
2. Update the template repos to use the British spelling

**Comment by AntonyBishop** [comment]
Sounds fair to me. Will update and resubmit a PR.

**Review by SteveMarshall — APPROVED** [review]
💯

**Pull request merged**
